### ISSUE TITLE
Duping drives

### ISSUE THREAD

**Issue by enough007** [SeanOMik/EnergeticStorage#11]
When taking out drives from a ES system if you shift click them fast and then close the UI fast sometimes a couple of drives will be duped in your inventory and on the ES system, this includes any items those drives may hold.

Only seems to happen when the ES system has all drive slots full, I believe a quick cheap fix for this would be asking for confirmation every time u remove a drive?

**Comment by SeanOMik** [comment]
I'll take a look at it, thanks!

**Comment by SeanOMik** [comment]
Fixed in [0.5.1-SNAPSHOT](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.5.1-SNAPSHOT).
