### ISSUE TITLE
Item destroyed when inventory is full

### ISSUE THREAD

**Issue by Mathox** [SeanOMik/EnergeticStorage#13]
When taking an item from an ES system with full inventory it disappears if taken by shift+click.
Not a very frequent problem but can be pretty expensive if one is not careful.

**Comment by SeanOMik** [comment]
I'll take a look at it, thanks!

**Comment by SeanOMik** [comment]
Fixed in [0.5.1-SNAPSHOT](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.5.1-SNAPSHOT).
