### ISSUE TITLE
Non-stackable items being withdrawn in stacks

### ISSUE THREAD

**Issue by larson377** [SeanOMik/EnergeticStorage#14]
I really would like to implement this into my server, but items which should not be stackable are able to be put into an ES System, then withdrawn. images attached are what happens when I deposit 2 identical pickaxes, then withdraw them.
![image](https://user-images.githubusercontent.com/11427391/106959210-49da4880-6732-11eb-8c90-16004943cbe6.png)

![image](https://user-images.githubusercontent.com/11427391/106959312-670f1700-6732-11eb-9fa3-480322b93c66.png)

![image](https://user-images.githubusercontent.com/11427391/106959344-72624280-6732-11eb-8d6d-565338bcb316.png)

**Comment by SeanOMik** [comment]
Fixed in [0.5.1-SNAPSHOT](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.5.1-SNAPSHOT).
