### ISSUE TITLE
Cannot remove drives from the GUI

### ISSUE THREAD

**Issue by larson377** [SeanOMik/EnergeticStorage#15]
As the title says, I cannot left click, right click or shift-click the drives from the GUI into my inventory. Below is the console log I receive when I attempt to remove a drive.
![image](https://user-images.githubusercontent.com/11427391/106960140-8b1f2800-6733-11eb-9d05-0fa83f5ad23f.png)

This plugin is amazing regardless, and I appreciate the work you put into this!

**Comment by SeanOMik** [comment]
This might be fixed in fixed in [0.5.1-SNAPSHOT](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.5.1-SNAPSHOT).

**Comment by SeanOMik** [comment]
I'm guessing this was fixed since no response
