### ISSUE TITLE
1.16.5 Spigot Not working + Textures not loading -Plugins conflict

### ISSUE THREAD

**Issue by idnthvn** [SeanOMik/EnergeticStorage#17]
On latest 1.16.5 Spigot, i get the same error as others of the BlockPlace being NULL. 
I also am using itemadder + Craftory Tech which have custom blocks and items, where it uses a resource pack. Your ES System only shows as a PLAYER head. Assuming this is caused by the resource pack overriding. Any way to split apart your png file and the player_head info so myself and others can merge the resource/textures together? Thank you

**Comment by SeanOMik** [comment]
I think the player head issue is because it wasn't supporting 1.16.5. Try the new [release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.6.0-SNAPSHOT) and tell me if it fixes the player head thing.

**Comment by SeanOMik** [comment]
Guessing this is fixed
