### ISSUE TITLE
Cant seem to get hoppers to connect!

### ISSUE THREAD

**Issue by colue** [SeanOMik/EnergeticStorage#21]
would love to use this plugin but i need to know if im crazy or not doing it right when i test but hoppers will not connect to the system in any way please help

**Comment by SeanOMik** [comment]
EnergeticStorage doesn't support putting items in from a hopper. However, it is a planned feature that I'll be adding when I have time.

**Comment by SeanOMik** [comment]
I just finished something that seems to work, but I'm worried about the performance impact. Would you be willing to test it for me?

**Comment by colue** [comment]
would love to

**Comment by SeanOMik** [comment]
Here's the [download](https://file.io/NwZ41dUfNSez). The file will be deleted from that website when it's downloaded. Tell me if you find any bugs related to the hoppers.

**Comment by colue** [comment]
will do

**Comment by colue** [comment]
so far its been working great no memory issues that i can see from the plugin

**Comment by SeanOMik** [comment]
Awesome, thanks for the help! I'll make a release later today probably.

**Comment by colue** [comment]
cool i have 2 of them up and no issues
