### ISSUE TITLE
i cant craft es systems or drives

### ISSUE THREAD

**Issue by Ethmangameon** [SeanOMik/EnergeticStorage#23]
it says when i type /pl that energetic storage is working so idk what could fix it i tried deleting config i tried restarting the server idk what could be wrong

**Comment by SeanOMik** [comment]
Do you get any errors inside of the console?

**Comment by Ethmangameon** [comment]
> Do you get any errors inside of the console?

no i did not its weird

**Comment by Ethmangameon** [comment]
does this plugin have ANY dependancys?

**Comment by Ethmangameon** [comment]
this is what happens
![2021-07-05_01 19 34](https://user-images.githubusercontent.com/84059085/124421281-204c3a00-dd2f-11eb-94a2-c367dc5aa09d.png)

**Comment by Ethmangameon** [comment]
also like i said the plugin shows up as loaded 
![2021-07-05_01 20 33](https://user-images.githubusercontent.com/84059085/124421342-4245bc80-dd2f-11eb-83c3-37d04e286dbc.png)

**Comment by Ethmangameon** [comment]
the log
[latest.log](https://github.com/SeanOMik/EnergeticStorage/files/6761878/latest.log)

**Comment by SeanOMik** [comment]
The plugin does have dependencies, one is built into the plugin, and another one can be interfered with by other plugins, but there would be errors. I added some debug stuff that should throw errors if it fails to register recipes. Could you [download this](https://drive.google.com/file/d/1_-8Ol89d_ICrSjQo6_P931Uuztmt745m/view?usp=sharing) and send the log?

**Comment by Ethmangameon** [comment]
okay here
[latest.log](https://github.com/SeanOMik/EnergeticStorage/files/6765753/latest.log)

**Comment by Ethmangameon** [comment]
sorry it took so long just woke up

**Comment by Ethmangameon** [comment]
could this plugin be the issue https://www.spigotmc.org/resources/customrecipeapi-1-13.74134/

**Comment by SeanOMik** [comment]
> 
> 
> could this plugin be the issue https://www.spigotmc.org/resources/customrecipeapi-1-13.74134/

That _could_ be the issue, try to disable it.

**Comment by Ethmangameon** [comment]
i did it didnt help

**Comment by Ethmangameon** [comment]
idk what could be interfering with the crafting

**Comment by SeanOMik** [comment]
I don't either. Could you make a server that runs just on your PC or something, with no plugins besides EnergeticStorage?

**Comment by Ethmangameon** [comment]
my server does run on my pc

**Comment by Ethmangameon** [comment]
it works on my test server so its a plugin incompatibility

**Comment by Ethmangameon** [comment]
I found the problem plugin https://www.spigotmc.org/resources/%E2%AD%90-nova-%E2%AD%90-1-17-%E2%9C%85-modpack-like-%E2%9C%A8-fully-configurable-%E2%9C%A8.93648/ could you in the future try to add compatibility for other plugins like this okay.

**Comment by SeanOMik** [comment]
Hm, that kind of sucks because that plugin actually looks pretty cool. Submit an issue on their github. Glad to hear you got it working though!

**Comment by SeanOMik** [comment]
@Ethmangameon I actually made [an issue](https://github.com/xenondevs/Nova/issues/7) on Nova's GitHub about the issue, and they fixed it and it will be in the next release of their plugin.
