### ISSUE TITLE
Drives are deleted on restart[Bug] 

### ISSUE THREAD

**Issue by AbsolutePhoenix** [SeanOMik/EnergeticStorage#25]
**Describe the bug**
Dives are disappearing and deleting items that where added when server is rebooted. This is happening in 1.17

**To Reproduce**
1. Place the controller.
2. Add drives to the drive GUI and fill with items
3. reboot the server and the drives disappear. 

**Expected behavior**
Add items to drives restart server and drives are still in tact and haven't been deleted. 

**Errors**
No errors present in log files

**Versions**
MC: 1.17
Java: "16.0.1" 2021-04-20

**Comment by Chew** [comment]
Can reproduce if you put items in the drive, keep the GUI open, then restart.
