### ISSUE TITLE
Doesn't work at all!

### ISSUE THREAD

**Issue by shmezi** [SeanOMik/EnergeticStorage#3]

**Comment by SeanOMik** [comment]
What spigot version, plugin version, and minecraft version are you using? Are there any console errors?

**Comment by GamingWubba93** [comment]
> _No description provided._

Bruh... How can a developer help you if you don't explain what is happening? Take a look at the **[CLOSED](https://github.com/SeanOMik/EnergeticStorage/issues/1)** Issues to see how to write a proper bug report.

**Comment by SeanOMik** [comment]
I'm just gonna close this due to him not providing information about the issue even after I ask him for it.
