### ISSUE TITLE
Loss of items while shifting into Full Inventory

### ISSUE THREAD

**Issue by lennartadrian-main** [SeanOMik/EnergeticStorage#35]
The Items get substractet from the system but they wont get into the Inventory

1. Place Many Items in the System  and get a full Inventory
2. Take Items from the system and watch the Amount left in the system

**Expected behavior**
The Amount should be the same or the Items will get droped in front of the Player

**Versions**
MC: 1.18.1
Java 17

**Comment by SeanOMik** [comment]
I haven't been able to reproduce it. Do you get any errors in the console?

**Comment by lennartadrian-main** [comment]
Just tried to reproduce it and found that it works fine with only one drive, but if there are two drives with the same Item type, the items get lost

**Comment by SeanOMik** [comment]
Hmm, still not able to reproduce it. I found some weird behavior that might cause it, but not sure if it does. I fixed that behavior. Could you try [this .jar](https://drive.google.com/file/d/1fCCZlajR7F3xyP-nHOBhWT62JhQIkQ34/view?usp=sharing) and tell me if fixing that behavior also fixes this bug?

**Comment by lennartadrian-main** [comment]
it fixed the bug

**Comment by SeanOMik** [comment]
Awesome, glad to hear. I'll make an "official" release soon
