### ISSUE TITLE
[Bug] Taking items out of the GUI

### ISSUE THREAD

**Issue by MinecollYT** [SeanOMik/EnergeticStorage#38]
**Describe the bug**

**To Reproduce**
1. Hold down SHIFT
2. LEFT-CLICK on the glass panes

**Expected behavior**
You can take the glass panes out of the GUI when pressing SHIFT + LEFT-CLICK

**Errors**
none

**Screenshots**
https://youtu.be/xhMz5sRcvfE

**Versions**
MC: 1.17.1
Java: Java 17

**Additional context**
none

**Comment by MinecollYT** [comment]
Plugin Version: 0.7.5-SNAPSHOT

**Comment by SeanOMik** [comment]
Just fixed it in the latest commit. I'll make a release soon

**Comment by SeanOMik** [comment]
Forgot to make a release for this, but it's in the [latest release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.7.6-SNAPSHOT) @MinecollYT
