### ISSUE TITLE
issues with energeticstorage loading

### ISSUE THREAD

**Issue by TechDoesGames** [SeanOMik/EnergeticStorage#42]
im having some issues with energetic storage loading, and its giving this error here:
[Pastebin for Latest.log](https://pastebin.com/gU7TkPFD)

**Comment by SeanOMik** [comment]
The plugin isn't updated for 1.18.2, working on it right now.

**Comment by TechDoesGames** [comment]
alright thanks :)

**Comment by SeanOMik** [comment]
Just made a [release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.7.6-SNAPSHOT) for 1.18.1, enjoy!
