### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by adamsanchez1219** [SeanOMik/EnergeticStorage#43]
**Describe the bug**
Drive duping glitch.

**To Reproduce**
1. Open gui menu with the drives.
2. Shift + Left Click the drive.
3. Multiple drives duped in inventory.

**Expected behavior**
Behavior similar to Bug #38.

**Errors**
If any errors or stack traces appeared in the console, please link to them here. Please use Pastebin to post stack traces. Don't paste them into the issue.

**Screenshots**

**Versions**
MC: 1.18.2
Java: 1.18.2

**Additional context**

**Comment by SeanOMik** [comment]
I'm assuming this is no longer an issue since you closed it @adamsanchez1219?
