### ISSUE TITLE
Working in 1.18.2?

### ISSUE THREAD

**Issue by OddTheAnomaly** [SeanOMik/EnergeticStorage#47]
I tried installing this on a 1.18.2 papermc server and it's not working. 

24.05 20:50:34 [Server] ERROR Error occurred while enabling EnergeticStorage v0.7.5-SNAPSHOT (Is it up to date?)

I'm assuming it's working in 1.18.1, if i'm wrong feel free to correct me, but are you planning an update if so?

**Comment by SeanOMik** [comment]
> I tried installing this on a 1.18.2 papermc server and it's not working.
> 
> 24.05 20:50:34 [Server] ERROR Error occurred while enabling EnergeticStorage v0.7.5-SNAPSHOT (Is it up to date?)
> 
> I'm assuming it's working in 1.18.1, if i'm wrong feel free to correct me, but are you planning an update if so?

I didn't test it on 1.18.2 so it's likely that version. Could you provide a full log during start up?



> This is a great mod!
> 
> Are you planning to update to Minecraft 1.19 version? (Please)

Yes I am! I just saw that 1.19 was released. I just made an issue for it so you can track the progress there. #49

**Comment by SeanOMik** [comment]
@OddTheAnomaly the [release for 1.19](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.7.7-SNAPSHOT) also supports 1.18.2.
