### ISSUE TITLE
Game-breaking issues :(

### ISSUE THREAD

**Issue by justablob** [SeanOMik/EnergeticStorage#7]
1. Search function doesn't work.
2. Taking drives out of the system and putting them back in will make them, and all items in them disappear. Now this is really bad. Lost all my items this way.

**Comment by SeanOMik** [comment]
What MC version are you using and what plugin version?

**Comment by justablob** [comment]
1.16.1, 0.3.

**Comment by SeanOMik** [comment]
Okay, well life is starting to get pretty busy so when it slows down I'll take a look.
