### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/EnergeticStorage#8]
My server is on 1.16.2, which is likely the reason that it is not working, but I can't do anything with it because the main command isn't working. The auto-complete is trying to use our nicknames on the server, and when I use those I get kicked from my own server with the message "Illegal characters in chat" no item was placed in my inventory when I logged back in. 

- If I type out my actual username without the autocomplete in-game, I get the "unexpected error occurred" message.

- If I type out the command in the server console, I get this error: "Unhandled exception executing command 'esgive' in plugin EnergeticStorage v0.3-SNAPSHOT"

Hopefully you can help with this because I've been having a lot of problems with our current Deep Storage option and was hoping this one would save us! Thanks :D

**Comment by SeanOMik** [comment]
I haven't tested it on 1.16.2 but I don't see any reason it wouldn't work. Could you send me the entire log on your server so I could see where exactly in the code these errors are happening?

**Comment by SavagePanda116** [comment]
Of course! Here's our latest.log.

[latest.log](https://github.com/SeanOMik/EnergeticStorage/files/5165596/latest.log)

**Comment by SeanOMik** [comment]
Fixed! Download the [latest release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.4-SNAPSHOT)
