### ISSUE TITLE
Cannot open system

### ISSUE THREAD

**Issue by SavagePanda116** [SeanOMik/EnergeticStorage#9]
Hi again!

Thank you so much for helping with the issues we had not being able to use the command last night, I appreciate the fast support! The command is working, but now we aren't able to open the system. I'm able to craft and place the ES System, but can't open it. There are no errors, just nothing happens. 

Also, after breaking the ES System, when it is back in an inventory, it's name is "Player Head" instead of "ES System", I'm not sure if that matters or not.

Thanks again for any help.

**Comment by SeanOMik** [comment]
Hm, I should've tested it completely before I released it. After I'm done with school work I'll take a look at it.

**Comment by SeanOMik** [comment]
Okay, try the [latest release](https://github.com/SeanOMik/EnergeticStorage/releases/tag/0.4-SNAPSHOT) and tell me if that worked

**Comment by SavagePanda116** [comment]
It's working! Thank you so much!!

**Comment by SeanOMik** [comment]
No problem
